# Generated by Django 3.0.6 on 2020-05-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatbot',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.CharField(default='', max_length=255),
        ),
    ]
