# Generated by Django 3.0.6 on 2020-05-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20200524_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='qaforbot',
            name='question_slug',
            field=models.SlugField(default=''),
        ),
    ]
