# Generated by Django 3.0.6 on 2020-05-22 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200522_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rest_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to='main.RestaurantType'),
        ),
    ]
