# Generated by Django 3.0.6 on 2020-05-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_restaurant_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='restauranttype',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.City'),
        ),
    ]
