# Generated by Django 3.0.6 on 2020-05-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_restauranttype_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='postal_code',
            field=models.CharField(default='', max_length=16),
        ),
    ]
