# Generated by Django 3.0.6 on 2020-05-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200523_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(),
        ),
    ]
