# Generated by Django 3.0.6 on 2020-05-31 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200531_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
